In [65]:
import pandas as pd 
import numpy as np

# Loading and cleaning data

In [66]:
# Loading the second sheet of the Excel file
data = pd.read_excel('data/data.xlsx', sheet_name=2)
data

,Unnamed: 0,Company Name,ISO Country Code,Country,City,Address,NACE Rev. 2 Code principal,"NACE Principal Rev. 2, description",Sector,Main activity,...,Turnover\nmEUR 2019,Operating margin 2019,Operating margin 2020,Operating margin 2021,Weighted Average Operating margin 2019-2021,Disponibilités données financières,2 années de pertes consécutives,Perte moyenne sur 3 ans,Reason for rejection,Selected companies
0,1.0,ITX HELLAS SINGLE MEMBER S.A.,GR,Grèce,ATHENS,NaN,4771.0,Commerce de détail d'habillement en magasin sp...,Engaged in the retail of fashion clothing,Retail,...,299.740253,0.072401,0.049671,0.068215,0.063472,YES,NO,NO,NaN,NaN
1,2.0,RANDEVU,RU,Fédération de Russie,MOSCOW,"UL. SKAKOVAYA D. 17, STR. 2, KOM. 2",4772.0,Commerce de détail de chaussures et d'articles...,Engaged in the wholesale trade and marketing o...,Wholesale,...,336.80946,0.004001,0.059199,0.050258,0.034774,YES,NO,NO,NaN,NaN
2,3.0,ZEEMAN TEXTIELSUPERS,FR,France,PARIS,NaN,4771.0,Commerce de détail d'habillement en magasin sp...,Engaged in the retail sale of clothing and out...,Retail,...,147.293323,0.028345,0.022492,0.023475,0.024776,YES,NO,NO,NaN,NaN
3,4.0,ANSWEAR.COM S.A.,PL,Pologne,KRAKOW,NaN,4771.0,Commerce de détail d'habillement en magasin sp...,Digital platform for the sale of branded cloth...,Wholesale; Retail; Services,...,73.054492,0.016668,0.060801,0.052874,0.046667,YES,NO,NO,NaN,NaN
4,5.0,REGENT GOLD,RU,Fédération de Russie,"AGALATOVSKOE SELSKOE POSELENIE, D. SKOTNOE","UL. SAVUSHKINA D. 126, LIT. A, POMESHCH. 133-N",4777.0,Commerce de détail d'articles d'horlogerie et ...,Operates as other miscellaneous store retailer,Retail,...,116.821429,0.039111,0.153764,0.158644,0.118483,YES,NO,NO,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
410,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Minimum,-0.088692,-0.188727,-0.062774,0.000364,NaN,NaN,NaN,NaN,NaN
411,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1st quartile,0.021437,0.012819,0.036817,0.028411,NaN,NaN,NaN,NaN,NaN
412,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Median,0.048105,0.043029,0.073872,0.056793,NaN,NaN,NaN,NaN,NaN
413,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3rd quartile,0.093577,0.084719,0.122645,0.099799,NaN,NaN,NaN,NaN,NaN
414,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Maximum,0.352348,0.321641,4.517579,1.270719,NaN,NaN,NaN,NaN,NaN

In [67]:
# Drop rows for which we have no company name
data = data[~data["Company Name"].isna()]

In [68]:
# Dropping the first column which is the index
data.drop(columns=["Unnamed: 0"], inplace=True)
data.head()

/var/folders/k7/yjlj1gk15bj1gjrxppqlsy9r0000gn/T/ipykernel_40104/2604145159.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.drop(columns=["Unnamed: 0"], inplace=True)

,Company Name,ISO Country Code,Country,City,Address,NACE Rev. 2 Code principal,"NACE Principal Rev. 2, description",Sector,Main activity,Description in Original language,...,Turnover\nmEUR 2019,Operating margin 2019,Operating margin 2020,Operating margin 2021,Weighted Average Operating margin 2019-2021,Disponibilités données financières,2 années de pertes consécutives,Perte moyenne sur 3 ans,Reason for rejection,Selected companies
0,ITX HELLAS SINGLE MEMBER S.A.,GR,Grèce,ATHENS,NaN,4771.0,Commerce de détail d'habillement en magasin sp...,Engaged in the retail of fashion clothing,Retail,NaN,...,299.740253,0.072401,0.049671,0.068215,0.063472,YES,NO,NO,NaN,NaN
1,RANDEVU,RU,Fédération de Russie,MOSCOW,"UL. SKAKOVAYA D. 17, STR. 2, KOM. 2",4772.0,Commerce de détail de chaussures et d'articles...,Engaged in the wholesale trade and marketing o...,Wholesale,реализация обуви и аксессуаров,...,336.80946,0.004001,0.059199,0.050258,0.034774,YES,NO,NO,NaN,NaN
2,ZEEMAN TEXTIELSUPERS,FR,France,PARIS,NaN,4771.0,Commerce de détail d'habillement en magasin sp...,Engaged in the retail sale of clothing and out...,Retail,"Négoce au détail ou en gros de vêtements, acce...",...,147.293323,0.028345,0.022492,0.023475,0.024776,YES,NO,NO,NaN,NaN
3,ANSWEAR.COM S.A.,PL,Pologne,KRAKOW,NaN,4771.0,Commerce de détail d'habillement en magasin sp...,Digital platform for the sale of branded cloth...,Wholesale; Retail; Services,NaN,...,73.054492,0.016668,0.060801,0.052874,0.046667,YES,NO,NO,NaN,NaN
4,REGENT GOLD,RU,Fédération de Russie,"AGALATOVSKOE SELSKOE POSELENIE, D. SKOTNOE","UL. SAVUSHKINA D. 126, LIT. A, POMESHCH. 133-N",4777.0,Commerce de détail d'articles d'horlogerie et ...,Operates as other miscellaneous store retailer,Retail,Торговля ювелирными изделиями,...,116.821429,0.039111,0.153764,0.158644,0.118483,YES,NO,NO,NaN,NaN

In [69]:
data.columns

Index(['Company Name', 'ISO Country Code', 'Country', 'City', 'Address',
       'NACE Rev. 2 Code principal', 'NACE Principal Rev. 2, description ',
       'Sector', 'Main activity', 'Description in Original language',
       'Description in English', 'Website',
       'Operating result [=EBIT]\nmEUR 2021',
       'Operating result [=EBIT]\nmEUR 2020',
       'Operating result [=EBIT]\nmEUR 2019', 'Turnover\nmEUR 2021',
       'Turnover\nmEUR 2020', 'Turnover\nmEUR 2019', 'Operating margin 2019',
       'Operating margin 2020', 'Operating margin 2021',
       'Weighted Average Operating margin 2019-2021',
       'Disponibilités données financières', '2 années de pertes consécutives',
       'Perte moyenne sur 3 ans', 'Reason for rejection',
       'Selected companies'],
      dtype='object')

In [70]:
# No information in the following columns, columns used for previous filtering
print(data["Disponibilités données financières"].value_counts())
print(data["Perte moyenne sur 3 ans"].value_counts())
print(data["Selected companies"].value_counts())
print(data["Reason for rejection"].value_counts())
print(data["2 années de pertes consécutives"].value_counts())

Disponibilités données financières
YES    407
Name: count, dtype: int64
Perte moyenne sur 3 ans
NO    407
Name: count, dtype: int64
Series([], Name: count, dtype: int64)
Series([], Name: count, dtype: int64)
2 années de pertes consécutives
NO    407
Name: count, dtype: int64

In [71]:
# Let us drop the columns that we won't be using   
columns_to_drop = [
    "Description in Original language",
    "Disponibilités données financières",
    "Perte moyenne sur 3 ans",
    "Selected companies",
    "Reason for rejection",
    "2 années de pertes consécutives"
]
data = data.drop(columns=columns_to_drop)
data.tail()

,Company Name,ISO Country Code,Country,City,Address,NACE Rev. 2 Code principal,"NACE Principal Rev. 2, description",Sector,Main activity,Description in English,...,Operating result [=EBIT]\nmEUR 2021,Operating result [=EBIT]\nmEUR 2020,Operating result [=EBIT]\nmEUR 2019,Turnover\nmEUR 2021,Turnover\nmEUR 2020,Turnover\nmEUR 2019,Operating margin 2019,Operating margin 2020,Operating margin 2021,Weighted Average Operating margin 2019-2021
402,BIONDI S.R.L.,IT,Italie,VERCELLI,CORSO LIBERTA' 41,4777.0,Commerce de détail d'articles d'horlogerie et ...,Primarily engaged in the wholesale trade of je...,Wholesale,Primarily engaged in the wholesale trade of je...,...,0.526155,0.676994,0.549799,4.311224,4.579774,6.494697,0.084654,0.147823,0.122043,0.113934
403,ARI S.R.L.,IT,Italie,VARESE,VIA CAMILLO BENSO CONTE DI CAVOUR 39,4771.0,Commerce de détail d'habillement en magasin sp...,NaN,NaN,NaN,...,0.986873,0.916360,0.344150,4.275292,5.887759,5.584542,0.061625,0.155638,0.230832,0.142713
404,KEEPSEA SL.,ES,Espagne,GUARDAMAR DEL SEGURA,NaN,4751.0,Commerce de détail de textiles en magasin spéc...,NaN,NaN,NaN,...,19.018429,1.894288,0.857535,4.209872,7.693404,5.228958,0.163997,0.246222,4.517579,1.270719
405,ZETEK SRL,IT,Italie,CERVIA,VIALE ROMAGNA 69/71,4771.0,Commerce de détail d'habillement en magasin sp...,Engaged in the manufacture and retail sale of ...,Manufacturing; Retail,Engaged in the manufacture and retail sale of ...,...,0.415383,0.397125,0.440186,4.183587,4.083184,4.969188,0.088583,0.097259,0.099289,0.094643
406,WADEL S.R.L.,IT,Italie,CAGLIARI,VIA DEL RISORGIMENTO 5,4772.0,Commerce de détail de chaussures et d'articles...,Primarily engaged in the retail sale of footwe...,Retail,Primarily engaged in the retail sale of footwe...,...,0.297215,0.274663,0.529682,4.002288,6.221574,9.889344,0.053561,0.044147,0.074261,0.054768

# Extracting the comparable companies

In [81]:
## Manufacturing & design companies
manuf_and_design_comps = data[data["Main activity"].str.contains(r"Manufacturing|Design", case=False, na=False)]
manuf_and_design_comps

,Company Name,ISO Country Code,Country,City,Address,NACE Rev. 2 Code principal,"NACE Principal Rev. 2, description",Sector,Main activity,Description in English,...,Operating result [=EBIT]\nmEUR 2021,Operating result [=EBIT]\nmEUR 2020,Operating result [=EBIT]\nmEUR 2019,Turnover\nmEUR 2021,Turnover\nmEUR 2020,Turnover\nmEUR 2019,Operating margin 2019,Operating margin 2020,Operating margin 2021,Weighted Average Operating margin 2019-2021
42,OOO JEWELLERY HOUSE KRISTALL (LIMITED LIABILIT...,RU,Fédération de Russie,LIPETSK,NaN,4777.0,Commerce de détail d'articles d'horlogerie et ...,"Engaged in the design, manufacture, and retail...",Manufacturing; Retail,"Engaged in the design, manufacture, and retail...",...,3.736436,3.680448,2.821143,31.525547,26.383879,37.695242,0.074841,0.139496,0.118521,0.107087
62,EMMEPI S.R.L.,IT,Italie,RIPALIMOSANI,VIALE UNITA' D'ITALIA 18,4772.0,Commerce de détail de chaussures et d'articles...,Specialises in manufacturing mechanical parts ...,Manufacturing,Specialises in manufacturing mechanical parts ...,...,1.661366,0.551261,1.018801,22.728831,18.917818,22.534004,0.045212,0.02914,0.073095,0.050349
67,CUPCAKE CLOTHING LIMITED,GB,Royaume-Uni,LONDON,NaN,4771.0,Commerce de détail d'habillement en magasin sp...,Engaged in the design and manufacture of clothing,Manufacturing,The design and manufacture of clothing.,...,0.675169,-0.397739,0.092973,22.331227,13.920585,21.88584,0.004248,-0.028572,0.030234,0.006371
71,PILAR PRIETO GUMIEL SL,ES,Espagne,ALCORCON,NaN,4771.0,Commerce de détail d'habillement en magasin sp...,Engaged in the production and retail distribut...,Manufacturing; Retail,Engaged in the production and retail distribut...,...,2.425306,-0.007340,2.147210,20.478868,15.217511,24.400023,0.088,-0.000482,0.11843,0.075964
151,SOLUX INVEST,BE,Belgique,WAREGEM,NaN,2611.0,Fabrication de composants électroniques,"Engaged in the development, manufacture and sa...",Manufacturing; Wholesale,"Engaged in the development, manufacture and sa...",...,3.358570,3.710702,4.047987,11.532561,11.536777,11.488617,0.352348,0.321641,0.291225,0.321699
155,HEREDEROS DE ANTONIO MOYA BARRIONUEVO SL,ES,Espagne,TORREMOLINOS,NaN,4771.0,Commerce de détail d'habillement en magasin sp...,Engaged in the manufacture and distribution of...,Manufacturing,Engaged in the manufacture and distribution of...,...,0.228999,0.141080,0.398780,11.295962,8.819832,11.375236,0.035057,0.015996,0.020273,0.024415
166,"ROFINOR - TEXTEIS, LDA",PT,Portugal,CARVALHOSA,NaN,4751.0,Commerce de détail de textiles en magasin spéc...,Engaged in the manufacture of workwear fabrics,Manufacturing,Engaged in the manufacture of workwear fabrics...,...,0.725929,1.151107,0.366906,10.874012,11.733458,10.224937,0.035883,0.098105,0.066758,0.068345
168,LARIO SPORT SL,ES,Espagne,VALENCIA,NaN,4772.0,Commerce de détail de chaussures et d'articles...,Engaged in the manufacture and sale of leather...,Manufacturing,Engaged in the manufacture and sale of leather...,...,0.651844,-1.234427,0.917537,10.783415,8.452433,13.405347,0.068446,-0.146044,0.060449,0.010262
207,VERONESI GIULIO S.R.L.,IT,Italie,BOLOGNA,PIAZZA ENZO RE 1/H,4777.0,Commerce de détail d'articles d'horlogerie et ...,Engaged in the manufacture and retail distribu...,Manufacturing; Retail,Engaged in the manufacture and retail distribu...,...,0.884902,0.476002,0.695345,8.822584,7.155758,8.280045,0.083978,0.06652,0.1003,0.084764
256,MARTA SRL,IT,Italie,MONTICELLO CONTE OTTO,VIA VENEZIA 5,4771.0,Commerce de détail d'habillement en magasin sp...,An Italy based enterprise engaged in the manuf...,Manufacturing; Wholesale,An Italy based enterprise engaged in the manuf...,...,0.750299,0.607754,0.394475,7.498943,5.802365,7.1072,0.055504,0.104742,0.100054,0.085872
261,GIOIELLERIA WARGAS SISTI DEI F.LLI MELANI S.R.L.,IT,Italie,ANCONA,CORSO GIUSEPPE GARIBALDI 39,4777.0,Commerce de détail d'articles d'horlogerie et ...,"Engaged in the manufacture, repair and retail ...",Manufacturing,"Engaged in the manufacture, repair and retail ...",...,0.361417,0.247477,0.239360,7.383005,5.951011,6.169668,0.038796,0.041586,0.048953,0.043492
285,ASKELAND AS,NO,Norvège,STAVANGER,NaN,4777.0,Commerce de détail d'articles d'horlogerie et ...,Engaged in the manufacture and sale of watches,Manufacturing; Retail; Services,Engaged in the manufacture and sale of watches...,...,0.807545,0.493639,0.313683,6.847566,5.503882,5.528491,0.056739,0.089689,0.117932,0.090317
358,TRADIZIONE MODA S.R.L.,IT,Italie,PAESE,VIA GIUSEPPE DI VITTORIO 2,4771.0,Commerce de détail d'habillement en magasin sp...,Engaged in the manufacture and distribution of...,Manufacturing; Wholesale,Engaged in the manufacture and distribution of...,...,0.496479,0.339056,0.668387,5.312463,4.261610,6.243713,0.10705,0.079561,0.093456,0.095078
405,ZETEK SRL,IT,Italie,CERVIA,VIALE ROMAGNA 69/71,4771.0,Commerce de détail d'habillement en magasin sp...,Engaged in the manufacture and retail sale of ...,Manufacturing; Retail,Engaged in the manufacture and retail sale of ...,...,0.415383,0.397125,0.440186,4.183587,4.083184,4.969188,0.088583,0.097259,0.099289,0.094643

Maybe we could keep companies that also do retail

In [77]:
# Exclude companies in sportswear
sportswear_companies = data[data["Description in English"].str.contains(r"Sportswear|Sports|Sport", case=False, na=False)]
sportswear_companies

,Company Name,ISO Country Code,Country,City,Address,NACE Rev. 2 Code principal,"NACE Principal Rev. 2, description",Sector,Main activity,Description in English,...,Operating result [=EBIT]\nmEUR 2021,Operating result [=EBIT]\nmEUR 2020,Operating result [=EBIT]\nmEUR 2019,Turnover\nmEUR 2021,Turnover\nmEUR 2020,Turnover\nmEUR 2019,Operating margin 2019,Operating margin 2020,Operating margin 2021,Weighted Average Operating margin 2019-2021
43,NEWPORT COLLECTION AB,SE,Suède,NORRKOPING,SODRA PROMENADEN 120,4771.0,Commerce de détail d'habillement en magasin sp...,Marketing and trade of home textiles and furni...,Wholesale,Bolaget skall bedriva forsaljning av hemtextil...,...,3.499650,1.311035,0.839064,29.594845,21.821266,13.273455,0.063214,0.060081,0.118252,0.087336
74,STADIO SPORT SOCIEDAD LIMITADA,ES,Espagne,ARUCAS,NaN,4771.0,Commerce de détail d'habillement en magasin sp...,Engaged in the operation of sporting goods store,Retail,Engaged in the operation of sporting goods sto...,...,2.509528,1.072502,2.022331,19.859520,18.326712,22.760117,0.088854,0.058521,0.126364,0.091956
98,ADRENALINE.PL SP. Z O.O. SP.K.,PL,Pologne,OLSZTYN,NaN,4771.0,Commerce de détail d'habillement en magasin sp...,Engaged in the retail of sportswear,Retail,Engaged in the retail of sportswear [source: B...,...,2.218836,0.888782,1.915227,15.863709,13.218327,17.978894,0.106526,0.067239,0.139869,0.106731
121,BIG BRAND SOLE SHAREHOLDER CO. LTD,GR,Grèce,RETHYMNO,NaN,4771.0,Commerce de détail d'habillement en magasin sp...,Operates as an online clothing store that cate...,Retail,"Trade of sportswear, sports shoes and sports g...",...,1.269439,0.231812,-0.548456,13.923971,11.848299,12.306058,-0.044568,0.019565,0.091169,0.025022
167,SPORT & MODA D.O.O.,HR,Croatie,ZADAR,NaN,4771.0,Commerce de détail d'habillement en magasin sp...,NaN,NaN,"-maloprodaja sportske odjece, obuce i opreme p...",...,1.705366,0.530917,0.325195,10.795955,6.953313,6.832868,0.047593,0.076355,0.157963,0.104201
292,DEDICATED SWEDEN AB,SE,Suède,STOCKHOLM,ALSTAVIKSVAGEN 3,4771.0,Commerce de détail d'habillement en magasin sp...,NaN,NaN,Foremalet for bolagets verksamhet ar handel me...,...,0.369949,0.143608,0.241221,6.676758,4.999185,4.427658,0.054481,0.028726,0.055408,0.04687
394,MARMON SPORTS,FR,France,AUBERVILLIERS,NaN,4771.0,Commerce de détail d'habillement en magasin sp...,Engaged in the retail trade of sporting goods ...,Retail,Engaged in the retail trade of sporting goods ...,...,0.083331,-0.075603,0.126654,4.486321,4.838715,6.271068,0.020197,-0.015625,0.018574,0.008616

In [79]:
# Check the second one
print(sportswear_companies["Description in English"].iloc[1])

Engaged in the operation of sporting goods store [source: Bureau van Dijk]